#!/bin/bash
. /var/openpanel/api/sh/module.sh

SSLDIR=/etc/ssl/private
A2CONFDIR=/etc/apache2/sites-enabled

JoomlaAdmin.update() {
  appid=joomla
  newpass=$(coreval JoomlaAdmin password)
  awstats=$(coreval JoomlaAdmin awstatspass)
  MD5_PWD=$(echo -n ${newpass} | md5sum | cut -f 1 -d ' ')
  MD5_AWSTATS=$(echo -n ${awstats} | md5sum | cut -f 1 -d ' ')
  [ -z "${awstats}" ] || authd runscript openapp-call "awstats" passwd "MD5|$MD5_AWSTATS"
  authd runscript openapp-call "$appid" passwd "MD5|$MD5_PWD"
}

Module.getconfig() {
  cat << _EOF_
  <openpanel.module>
    <dict id="JoomlaAdmin" type="class">
      <dict id="Admin">
	    <string id="password">*</string>
      </dict>
    </dict>
  </openpanel.module>
_EOF_
  exitquiet
}


restart_apache2() {
cat <<EOB > $(pwd)/ssl-namevirtualhost.conf
NameVirtualHost *:443
EOB

	[ ! -f /etc/apache2/conf.d/ssl-namevirtualhost.conf ] && authd installfile ssl-namevirtualhost.conf /etc/apache2/conf.d

	authd reloadservice apache2
}

HTTPS.delete() {
	authd deletefile ${A2CONFDIR}/default-ssl.conf
	authd deletefile ${SSLDIR}/joomla.pem

	restart_apache2
}

HTTPS.create() {
	SSLCERT=$(coreval HTTPS pem)
	SSLIP=$(coreval HTTPS ip)

[ -z ${SSLIP} ] && SSLIP="*"

cat <<EOB > $(pwd)/joomla.pem
${SSLCERT}
EOB

/var/openpanel/bin/validatepem.py $(pwd)/joomla.pem

[ $? -eq 0 ] || exiterror "Your certificate has issues. Is the private key included (and without a passphrase)?"

cat <<EOB > $(pwd)/default-ssl.conf
<VirtualHost ${SSLIP}:443>
	DocumentRoot /var/www

	SSLEngine on
	SSLProtocol -all +TLSv1 +SSLv3
	SSLCertificateFile ${SSLDIR}/joomla.pem

    CustomLog /var/log/apache2/access.log combined
    ErrorLog /var/log/apache2/error.log
</VirtualHost>
EOB

	authd makedir ${SSLDIR}
	authd installfile joomla.pem ${SSLDIR}
	authd installfile default-ssl.conf ${A2CONFDIR}

	restart_apache2
}

HTTPS.update() {
    HTTPS.create
}

implement OpenAppJoomla.module
